# CH02_인과효과

---
## 2.1 노동시장에서 인종차별
---

```
Bertrand, Marianne, and Sendhil Mullainathan. 2004. "Are Emily and Greg More Employable Than Lakisha and Jamal? A Field Experiment on Labor Market Discrimination." American Economic Review 94 (4): 991–1013.
DOI: 10.1257/0002828042002561

In [1]:
import numpy as np
import pandas as pd

In [2]:
resume = pd.read_csv('data/resume.csv')

In [3]:
resume.shape

(4870, 4)

In [4]:
resume.head(6)

  firstname     sex   race  call
0   Allison  female  white     0
1   Kristen  female  white     0
2   Lakisha  female  black     0
3   Latonya  female  black     0
4    Carrie  female  white     0
5       Jay    male  white     0

In [5]:
resume.dtypes

firstname      str
sex            str
race           str
call         int64
dtype: object

In [8]:
resume.describe()

              call
count  4870.000000
mean      0.080493
std       0.272083
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [14]:
for col in resume.columns[:3]:
    print(resume[col].value_counts())
    print()

firstname
Tamika      256
Anne        242
Allison     232
Latonya     230
Emily       227
Latoya      226
Kristen     213
Ebony       208
Tanisha     207
Jill        203
Lakisha     200
Kenya       196
Laurie      195
Sarah       193
Meredith    187
Keisha      183
Aisha       180
Carrie      168
Neil         76
Tyrone       75
Tremayne     69
Todd         68
Jay          67
Matthew      67
Rasheed      67
Brendan      65
Leroy        64
Kareem       64
Brad         63
Jamal        61
Geoffrey     59
Brett        59
Hakim        55
Jermaine     52
Greg         51
Darnell      42
Name: count, dtype: int64

sex
female    3746
male      1124
Name: count, dtype: int64

race
white    2435
black    2435
Name: count, dtype: int64

In [15]:
race_call_tab = pd.crosstab(resume.race, resume.call)
race_call_tab

call      0    1
race
black  2278  157
white  2200  235

In [16]:
pd.crosstab(resume.race, resume.call, margins=True)

call      0    1   All
race
black  2278  157  2435
white  2200  235  2435
All    4478  392  4870

In [19]:
race_call_tab.iloc[:,1].sum() / resume.shape[0]

np.float64(0.08049281314168377)

In [20]:
race_call_tab.loc['black', 1] / race_call_tab.loc['black'].sum()

np.float64(0.06447638603696099)

In [21]:
race_call_tab.loc['white', 1] / race_call_tab.loc['white'].sum()

np.float64(0.09650924024640657)

In [23]:
race_call_tab.iloc[0]

call
0    2278
1     157
Name: black, dtype: int64

In [25]:
race_call_tab.iloc[:, 1]

race
black    157
white    235
Name: 1, dtype: int64

In [26]:
(race_call_tab.loc['white', 1] / race_call_tab.loc['white'].sum()) - (race_call_tab.loc['black', 1] / race_call_tab.loc['black'].sum())

np.float64(0.032032854209445585)

In [27]:
resume['call'].mean()

np.float64(0.08049281314168377)

---
## 2.2 데이터 부분 선택
---

### 2.2.1: Boolean Values and Logical Operat

In [28]:
type(True)

bool

In [29]:
int(True)

1

In [30]:
int(False)

0

In [33]:
x = pd.Series([True, False, True])
x.mean().round(2)

np.float64(0.67)

In [35]:
x.sum()

np.int64(2)

In [36]:
False & True

False

In [37]:
True | False

True

In [38]:
False | False

False

In [39]:
True & False & True

False

In [40]:
(True | False) & False

False

In [41]:
True | (False & False)

True

In [42]:
TF1 = pd.Series([True, False, False])
TF2 = pd.Series([True, False, True])
TF1 | TF2

0     True
1    False
2     True
dtype: bool

In [43]:
TF1 & TF2

0     True
1    False
2    False
dtype: bool

### 2.2.2: Relational Operators

In [44]:
4 > 3

True

In [45]:
'Hello' == 'hello'

False

In [46]:
'Hello' != 'hello'

True

In [47]:
x = pd.Series([3,2,1,-2,-1])
x >= 2

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [49]:
x != 1

0     True
1     True
2    False
3     True
4     True
dtype: bool

In [51]:
(x > 0) & (x <= 2)

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [52]:
(x > 2) | (x <= -1)

0     True
1    False
2    False
3     True
4     True
dtype: bool

In [53]:
x_int = (x > 0) & (x <= 2)
x_int

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [54]:
x_int.mean()

np.float64(0.4)

In [55]:
x_int.sum()

np.int64(2)

### 2.2.3: Subsetting

In [56]:
resume['call'][resume['race'] == 'black'].mean()

np.float64(0.06447638603696099)

In [58]:
resume['race'][:5]

0    white
1    white
2    black
3    black
4    white
Name: race, dtype: str

In [57]:
resume['race'][:5] == 'black'

0    False
1    False
2     True
3     True
4    False
Name: race, dtype: bool

In [59]:
resume.shape

(4870, 4)

In [60]:
resumeB = resume.loc[resume['race'] == 'black'].copy()
resumeB.shape

(2435, 4)

In [61]:
resumeB['call'].mean()

np.float64(0.06447638603696099)

In [62]:
resumeBf = (
    resume.loc[(resume.race == 'black') & (resume.sex == 'female'), ['call', 'firstname']]
)

resumeBf.head(6)

    call firstname
2      0   Lakisha
3      0   Latonya
7      0     Kenya
8      0   Latonya
10     0     Aisha
12     0     Aisha

In [64]:
resumeBf = resume.loc[(resume.race == 'black') & (resume.sex == 'female')]
resumeBm = resume.loc[(resume.race == 'black') & (resume.sex == 'male')]
resumeWf = resume.loc[(resume.race == 'white') & (resume.sex == 'female')]
resumeWm = resume.loc[(resume.race == 'white') & (resume.sex == 'male')]

In [65]:
resumeWf['call'].mean() - resumeBf['call'].mean()

np.float64(0.0326468944913853)

In [66]:
resumeWm['call'].mean() - resumeBm['call'].mean()

np.float64(0.03040785618119901)

### 2.2.4: Simple Conditional Statements

In [67]:
resume['BlackFemale'] = (
    np.where(
        (resume.race == 'black') & (resume.sex == 'female'), 1, 0
    )
)

In [69]:
resume.head()

  firstname     sex   race  call  BlackFemale
0   Allison  female  white     0            0
1   Kristen  female  white     0            0
2   Lakisha  female  black     0            1
3   Latonya  female  black     0            1
4    Carrie  female  white     0            0

In [72]:
pd.crosstab([resume.race, resume.sex], resume.BlackFemale)

BlackFemale      0     1
race  sex
black female     0  1886
      male     549     0
white female  1860     0
      male     575     0

In [73]:
resume.drop('BlackFemale', axis=1, inplace=True)

### 2.2.5: Categorical Variables

In [74]:
cat_vars = ['firstname', 'sex', 'race']

resume[cat_vars] = resume[cat_vars].astype('category')
resume.dtypes

firstname    category
sex          category
race         category
call            int64
dtype: object

In [75]:
resume['race'][:5]

0    white
1    white
2    black
3    black
4    white
Name: race, dtype: category
Categories (2, str): ['black', 'white']

In [76]:
resume['race'].cat.categories

Index(['black', 'white'], dtype='str')

In [77]:
resume['race'].cat.codes

0       1
1       1
2       0
3       0
4       1
       ..
4865    0
4866    0
4867    1
4868    0
4869    1
Length: 4870, dtype: int8

In [78]:
resume['race'].value_counts()

race
black    2435
white    2435
Name: count, dtype: int64

In [79]:
resume['race'].value_counts(normalize=True)

race
black    0.5
white    0.5
Name: proportion, dtype: float64

In [81]:
resume[cat_vars].describe()

       firstname     sex   race
count       4870    4870   4870
unique        36       2      2
top       Tamika  female  black
freq         256    3746   2435

In [82]:
resume.describe(include='all')

       firstname     sex   race         call
count       4870    4870   4870  4870.000000
unique        36       2      2          NaN
top       Tamika  female  black          NaN
freq         256    3746   2435          NaN
mean         NaN     NaN    NaN     0.080493
std          NaN     NaN    NaN     0.272083
min          NaN     NaN    NaN     0.000000
25%          NaN     NaN    NaN     0.000000
50%          NaN     NaN    NaN     0.000000
75%          NaN     NaN    NaN     0.000000
max          NaN     NaN    NaN     1.000000

In [83]:
resume['type'] = ''
(resume.loc[(resume.race == 'black') & (resume.sex == 'female'), 'type']) = 'BlackFemale'
(resume.loc[(resume.race == 'black') & (resume.sex == 'male'), 'type']) = 'BlackMale'
(resume.loc[(resume.race == 'white') & (resume.sex == 'female'), 'type']) = 'WhiteFemale'
(resume.loc[(resume.race == 'white') & (resume.sex == 'male'), 'type']) = 'WhiteMale'

In [85]:
resume.dtypes

firstname    category
sex          category
race         category
call            int64
type              str
dtype: object

In [90]:
resume['type'].value_counts().index

Index(['BlackFemale', 'WhiteFemale', 'WhiteMale', 'BlackMale'], dtype='str', name='type')

In [92]:
conditions = [
    (resume.race == 'black') & (resume.sex == 'female'),
    (resume.race == 'black') & (resume.sex == 'male'),
    (resume.race == 'white') & (resume.sex == 'female')
]

choices = ['BlackFemale', 'BlackMale', 'WhiteFemale']

resume['type_alt'] = np.select(conditions, choices, 'WhiteMale')

resume['type'].equals(resume['type_alt'])

True

In [93]:
resume.drop('type_alt', axis=1, inplace=True)
resume.dtypes

firstname    category
sex          category
race         category
call            int64
type              str
dtype: object

In [94]:
resume['type'] = resume['type'].astype('category')
resume['type'].cat.categories

Index(['BlackFemale', 'BlackMale', 'WhiteFemale', 'WhiteMale'], dtype='str')

In [95]:
resume['type'].value_counts(sort=False)

type
BlackFemale    1886
BlackMale       549
WhiteFemale    1860
WhiteMale       575
Name: count, dtype: int64

In [97]:
resume.groupby('type')['call'].mean()

type
BlackFemale    0.066278
BlackMale      0.058288
WhiteFemale    0.098925
WhiteMale      0.088696
Name: call, dtype: float64

In [100]:
callback_name = resume.groupby('firstname')['call'].mean()
callback_name.sort_values().head(10)

firstname
Aisha       0.022222
Rasheed     0.029851
Keisha      0.038251
Tremayne    0.043478
Kareem      0.046875
Darnell     0.047619
Tyrone      0.053333
Hakim       0.054545
Tamika      0.054688
Lakisha     0.055000
Name: call, dtype: float64

In [101]:
callback_name.sort_values(ascending=False).head(10)

firstname
Brad        0.158730
Jay         0.134328
Kristen     0.131455
Carrie      0.130952
Meredith    0.101604
Sarah       0.098446
Laurie      0.097436
Jermaine    0.096154
Ebony       0.096154
Allison     0.094828
Name: call, dtype: float64

---
## 2.3 인과효과와 반사실
---

In [108]:
resume[:1]

  firstname     sex   race  call         type
0   Allison  female  white     0  WhiteFemale

In [111]:
resume.iloc[0]

firstname        Allison
sex               female
race               white
call                   0
type         WhiteFemale
Name: 0, dtype: object

---
## 2.4 무작위 대조시험
---

### 2.4.1 무작위의 역할

### 2.4.2 사회적 압박과 투표율

In [113]:
import os

In [114]:
os.getcwd()

'/home/user/repo/studies/qss'

In [115]:
os.chdir('/home/user/repo/studies/qss/data')

In [116]:
os.getcwd()

'/home/user/repo/studies/qss/data'

In [118]:
social = pd.read_csv('social.csv')
social.describe().round(2)

       yearofbirth  primary2004  primary2006     hhsize
count    305866.00    305866.00    305866.00  305866.00
mean       1956.21         0.40         0.31       2.18
std          14.45         0.49         0.46       0.79
min        1900.00         0.00         0.00       1.00
25%        1947.00         0.00         0.00       2.00
50%        1956.00         0.00         0.00       2.00
75%        1965.00         1.00         1.00       2.00
max        1986.00         1.00         1.00       8.00

In [119]:
social.info()

<class 'pandas.DataFrame'>
RangeIndex: 305866 entries, 0 to 305865
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   sex          305866 non-null  str
 1   yearofbirth  305866 non-null  int64
 2   primary2004  305866 non-null  int64
 3   messages     305866 non-null  str
 4   primary2006  305866 non-null  int64
 5   hhsize       305866 non-null  int64
dtypes: int64(4), str(2)
memory usage: 14.0 MB

In [120]:
social[['sex', 'messages']] = social[['sex', 'messages']].astype('category')
social['messages'].cat.categories

Index(['Civic Duty', 'Control', 'Hawthorne', 'Neighbors'], dtype='str')

In [121]:
social['messages']

0         Civic Duty
1         Civic Duty
2          Hawthorne
3          Hawthorne
4          Hawthorne
             ...
305861       Control
305862       Control
305863       Control
305864       Control
305865       Control
Name: messages, Length: 305866, dtype: category
Categories (4, str): ['Civic Duty', 'Control', 'Hawthorne', 'Neighbors']

In [123]:
social['messages'] = social['messages'].cat.reorder_categories(['Control', 'Civic Duty', 'Hawthorne', 'Neighbors'])
social['messages'].cat.categories

Index(['Control', 'Civic Duty', 'Hawthorne', 'Neighbors'], dtype='str')

In [125]:
social['messages'].cat.codes

0         1
1         1
2         2
3         2
4         2
         ..
305861    0
305862    0
305863    0
305864    0
305865    0
Length: 305866, dtype: int8

In [126]:
social['messages'].cat.ordered

False

In [128]:
social.groupby('messages')['primary2006'].mean()

messages
Control       0.296638
Civic Duty    0.314538
Hawthorne     0.322375
Neighbors     0.377948
Name: primary2006, dtype: float64

In [129]:
social['primary2006'][social.messages == 'Control'].mean()

np.float64(0.2966383083302395)

In [135]:
social.loc[:, 'primary2006'][social.messages == 'Control'].mean()

np.float64(0.2966383083302395)

In [136]:
(social.groupby('messages')['primary2006'].mean() - social['primary2006'][social.messages == 'Control'].mean())

messages
Control       0.000000
Civic Duty    0.017899
Hawthorne     0.025736
Neighbors     0.081310
Name: primary2006, dtype: float64

In [139]:
social['age'] = 2006 - social['yearofbirth']
social.groupby('messages')['age'].mean()

messages
Control       49.813546
Civic Duty    49.659035
Hawthorne     49.704795
Neighbors     49.852936
Name: age, dtype: float64

In [140]:
social.groupby('messages')['primary2004'].mean()

messages
Control       0.400339
Civic Duty    0.399445
Hawthorne     0.403230
Neighbors     0.406665
Name: primary2004, dtype: float64

In [141]:
social.groupby('messages')['hhsize'].mean()

messages
Control       2.183667
Civic Duty    2.189126
Hawthorne     2.180138
Neighbors     2.187770
Name: hhsize, dtype: float64